// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA63sJxau7JXDlYdFvCzeZMmMeS-tFnrSU',
    appId: '1:951790444921:web:66bdb720192441c0014fa8',
    messagingSenderId: '951790444921',
    projectId: 'waste-tagging-app',
    authDomain: 'waste-tagging-app.firebaseapp.com',
    storageBucket: 'waste-tagging-app.firebasestorage.app',
    measurementId: 'G-J0EEBLQRLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRlQEGHAHFkNb1gPZT09r-4Z0X8yi2DIA',
    appId: '1:951790444921:android:9cab8eda6cd98713014fa8',
    messagingSenderId: '951790444921',
    projectId: 'waste-tagging-app',
    storageBucket: 'waste-tagging-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC34Adu_9g_y4Y1UFUjgVeZDAjySGd7xQk',
    appId: '1:951790444921:ios:bd4a5d2626167bf1014fa8',
    messagingSenderId: '951790444921',
    projectId: 'waste-tagging-app',
    storageBucket: 'waste-tagging-app.firebasestorage.app',
    androidClientId: '951790444921-t61a420qkj3pnbh33c4lmilnqm2hrlc4.apps.googleusercontent.com',
    iosClientId: '951790444921-kuim672an7b3r2dqthakppi9jpvmaa4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteTaggingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC34Adu_9g_y4Y1UFUjgVeZDAjySGd7xQk',
    appId: '1:951790444921:ios:bd4a5d2626167bf1014fa8',
    messagingSenderId: '951790444921',
    projectId: 'waste-tagging-app',
    storageBucket: 'waste-tagging-app.firebasestorage.app',
    androidClientId: '951790444921-t61a420qkj3pnbh33c4lmilnqm2hrlc4.apps.googleusercontent.com',
    iosClientId: '951790444921-kuim672an7b3r2dqthakppi9jpvmaa4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteTaggingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA63sJxau7JXDlYdFvCzeZMmMeS-tFnrSU',
    appId: '1:951790444921:web:8ee6959d14d3dd95014fa8',
    messagingSenderId: '951790444921',
    projectId: 'waste-tagging-app',
    authDomain: 'waste-tagging-app.firebaseapp.com',
    storageBucket: 'waste-tagging-app.firebasestorage.app',
    measurementId: 'G-D85VKNE80C',
  );

}